using System;

namespace TestSpace;

[MFFYamlGeneratorTrigger_AttributeTypeLocator_LiquidBuilder_GeneratesClass_Attribute]
public class MFFYamlGeneratorTrigger_AttributeTypeLocator_LiquidBuilder_GeneratesClass_Source
{

}
